[template]
src = "ldapcert.tmpl"
dest = "/etc/openldap/certs/ldap-client.crt"
prefix = "/%%STACK%%/%%ENVIRONMENT%%/config"

keys = [
    "/ldap-cert"
]

reload_cmd = "/etc/openldap/restart-openldap.sh"
