[template]
src = "mozilla-ca.tmpl"
dest = "/etc/openldap/cacerts/mozilla.crt"
prefix = "/environments/%%ENVIRONMENT%%/global/ldap"

keys = [
    "/mozilla-ca"
]

reload_cmd = "/etc/openldap/restart-openldap.sh"
