#!/bin/bash
# Attempts to attach an ENI to an instance
# We assume that the interface will always be eth1

# Simple logging function
function log() {

    local LOGGER_BIN='/usr/bin/logger'
    local LOGMSG=$1

    [ -z "$LOGMSG" ] && { echo "Usage: $FUNCNAME [log message]"; exit 1; }

    # Set up the logger command if the binary is installed
    if [ ! -x $LOGGER_BIN ]; then
        # If logger is not installed just stderr it out
        echo "$LOGMSG"
    else
        $LOGGER_BIN --stderr --priority local7.info --tag ${BASH_SOURCE} "$LOGMSG"
    fi
}

# The beginning of variable central
eval $(curl -s -fq http://169.254.169.254/latest/user-data)

# Setup variables
INSTANCE_ID=$(curl -s -fq http://169.254.169.254/latest/meta-data/instance-id)
LOCAL_IP=$(curl -s -fq http://169.254.169.254/latest/meta-data/local-ipv4)
EC2_AVAIL_ZONE=$(curl -s -fq http://169.254.169.254/latest/meta-data/placement/availability-zone)
EC2_REGION=$(curl -s -fq http://169.254.169.254/latest/dynamic/instance-identity/document | jq '.region' -r)

# Stuff we need to attach ENI
SUBNET_ID=$(aws ec2 describe-instances --region ${EC2_REGION} --instance-ids ${INSTANCE_ID} --query "Reservations[*].Instances[*][SubnetId]" --output text)
ATTACHING_ENI=$(aws ec2 describe-network-interfaces  --region ${EC2_REGION} --filter Name=tag-key,Values=StackName Name=tag-value,Values=${NUBIS_STACK} --query "NetworkInterfaces[?Status == \`available\`][NetworkInterfaceId, SubnetId]" --output text | grep ${SUBNET_ID} | awk '{print $1}')
ENI_TO_IP=$(aws ec2 describe-network-interfaces --region ${EC2_REGION}  --filter --filter Name=network-interface-id,Values=${ATTACHING_ENI} --query "NetworkInterfaces[*].PrivateIpAddress" --output text)

if [[ "${ATTACHING_ENI}" ]]; then
    log "Attaching ENI ${ATTACHING_ENI} to instance ${INSTANCE_ID}"
    aws ec2 attach-network-interface --region ${EC2_REGION} --network-interface-id ${ATTACHING_ENI} --instance-id ${INSTANCE_ID} --device-index 1
    echo ${ATTACHING_ENI} > /var/tmp/eni_id
    RV=$?
    if [[ "${RV}" != 0 ]]; then
        log "ERROR: Unable to attach ENI ${ATTACHING_ENI} to instance ${INSTANCE_ID}"
        exit 1
    else
        log "SUCCESS: Successfully attached ENI ${ATTACHING_ENI} to instance ${INSTANCE_ID}"
    fi
fi
