#!/bin/bash
# During startup we need to elect a "leader" so that that host
# be the ldap sync server for the ldap slave
#
# Script also doubles up as a checker for consul service checks
#set -x

eval $(curl -s -fq http://169.254.169.254/latest/user-data)
INSTANCE_ID=$(curl -s -fq http://169.254.169.254/latest/meta-data/instance-id)
REGION=$(curl -s -fq http://169.254.169.254/latest/dynamic/instance-identity/document | jq '.region' -r)
MY_IP=$(curl -s  -fq http://169.254.169.254/latest/meta-data/local-ipv4)

# Simple logging function
function log() {

    local LOGGER_BIN='/usr/bin/logger'
    local LOGMSG=$1

    [ -z "$LOGMSG" ] && { echo "Usage: $FUNCNAME [log message]"; exit 1; }

    # Set up the logger command if the binary is installed
    if [ ! -x $LOGGER_BIN ]; then
        # If logger is not installed just stderr it out
        echo "$LOGMSG"
    else
        $LOGGER_BIN --stderr --priority local7.info --tag ${BASH_SOURCE} "$LOGMSG"
    fi
}

# Whats my ENI IP? We don't want to run describe instance everytime
# so we dump the eni ip to the filesystem and hope and pray it doesn't get overwritten
# if file does not exist and the size of the file is > 0 then we run the aws cli command
if [[ -f /var/tmp/eni_ip ]] && [[ -s /var/tmp/eni_ip ]]; then
    ENI_IP=$(cat /var/tmp/eni_ip)
else
    ENI_IP=$(aws ec2 describe-instances --instance-id ${INSTANCE_ID} --region ${REGION} --query "Reservations[*].Instances[*].NetworkInterfaces[*].PrivateIpAddresses[*].PrivateIpAddress" --output text | grep -v ${MY_IP})
    echo ${ENI_IP} > /var/tmp/eni_ip
fi

if [[ "$1" == "check" ]]; then
    # we don't really care about if this check passes or not really,
    # we're really only doing this so that we can make the check pass and
    # so that we can have consul actually re-run consul-do to get a new lock. Yes its a cheat i know
    /usr/local/bin/consul-do ${NUBIS_STACK}/${NUBIS_ENVIRONMENT} ${ENI_IP} DEBUG || exit 0
else
    /usr/local/bin/consul-do ${NUBIS_STACK}/${NUBIS_ENVIRONMENT} ${ENI_IP} || exit
    log "Electing ${INSTANCE_ID} with ENI IP ${ENI_IP} as leader and creating a lock"
fi
